"""empty message.

Revision ID: 4cbe34f35090
Revises: 7228fdf2572b
Create Date: 2026-02-08 13:00:02.897793

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
# revision identifiers, used by Alembic.
revision = '4cbe34f35090'
down_revision = None
branch_labels = "schema"
depends_on = None



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_context().bind
    db_name = bind.engine.url.database
    
    connection = op.get_context().connection
    db_name = connection.engine.url.database
    op.execute(f"ALTER DATABASE {db_name} SET timezone TO 'UTC';")

    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.Integer(), server_default=None, nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['category.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )

    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text("timezone('UTC', now())"), nullable=False),
    sa.Column('active', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column("quantity", sa.Integer(), server_default='0', nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('order_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), server_default='1', nullable=False),
    sa.Column('price_at_time', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_index(op.f('ix_category_id'), 'category', ['id'], unique=False)
    op.create_index(op.f('ix_client_id'), 'client', ['id'], unique=False)
    op.create_index(op.f('ix_order_id'), 'order', ['id'], unique=False)
    op.create_index(op.f('ix_order_item_id'), 'order_item', ['id'], unique=False)
    op.create_index(op.f('ix_product_id'), 'product', ['id'], unique=False)
    

    op.create_unique_constraint('uq_order_product', 'order_item', ['order_id', 'product_id'])
    # ### end Alembic commands ###

    
    op.create_index(op.f('ix_order_date'), 'order', ['date'], unique=False)


def downgrade() -> None:
    op.drop_index(op.f('ix_order_date'), table_name='order')
    
    op.drop_constraint('uq_order_product', 'order_item', type_='unique')

    op.drop_index(op.f('ix_product_id'), table_name='product')
    op.drop_index(op.f('ix_order_item_id'), table_name='order_item')
    op.drop_index(op.f('ix_order_id'), table_name='order')
    op.drop_index(op.f('ix_client_id'), table_name='client')
    op.drop_index(op.f('ix_category_id'), table_name='category')

    op.drop_table('order_item')
    op.drop_table('order')
    op.drop_table('client')
    op.drop_table('product')
    op.drop_table('category')
    # ### end Alembic commands ###
