"""initial

Revision ID: 807e835edae0
Revises:
Create Date: 2025-09-22 09:02:15.530689

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "807e835edae0"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("password", sa.String(length=255), nullable=False),
        sa.Column("active", sa.Integer(), server_default="1", nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username", name=op.f("username")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_constraint(op.f("username"), "user", type_="unique")
    op.drop_table("user")
    # ### end Alembic commands ###
