"""initial

Revision ID: 5546ad9a8231
Revises: 
Create Date: 2026-02-03 15:50:53.514142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5546ad9a8231'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.Integer(), server_default='1', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    # op.create_table('user',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('username', sa.String(length=255), nullable=False),
    # sa.Column('password', sa.String(length=255), nullable=False),
    # sa.Column('active', sa.Integer(), server_default='1', nullable=False),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('username')
    # )
  
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('category')
    # ### end Alembic commands ###
