"""default

Revision ID: ede40ca1cd98
Revises: 07ff32d52882
Create Date: 2026-02-05 16:59:39.155776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ede40ca1cd98'
down_revision: Union[str, None] = '07ff32d52882'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_category_id'), 'category', ['id'], unique=False)
    op.create_index(op.f('ix_client_id'), 'client', ['id'], unique=False)
    op.create_index(op.f('ix_order_id'), 'order', ['id'], unique=False)
    op.create_index(op.f('ix_order_item_id'), 'order_item', ['id'], unique=False)
    op.create_index(op.f('ix_product_id'), 'product', ['id'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_product_id'), table_name='product')
    op.drop_index(op.f('ix_order_item_id'), table_name='order_item')
    op.drop_index(op.f('ix_order_id'), table_name='order')
    op.drop_index(op.f('ix_client_id'), table_name='client')
    op.drop_index(op.f('ix_category_id'), table_name='category')
    # ### end Alembic commands ###
