"""unique constraint

Revision ID: 75d5089c98f0
Revises: ede40ca1cd98
Create Date: 2026-02-05 17:46:03.697024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75d5089c98f0'
down_revision: Union[str, None] = 'ede40ca1cd98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_order_product', 'order_item', ['order_id', 'product_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_order_product', 'order_item', type_='unique')
    # ### end Alembic commands ###
