"""empty message.

Revision ID: 7228fdf2572b
Revises: 
Create Date: 2026-02-08 12:56:43.367875

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.orm import Session
from service.db_setup.models import Category, Product
from service.db_setup.models import Base


# revision identifiers, used by Alembic.
revision = '7228fdf2572b'
down_revision = None
branch_labels = "data"
depends_on = '4cbe34f35090'

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = Session(bind=bind)
    
    category0 = Category(title="Electronics")

    session.add(category0)
    session.flush()
    category_0_id = category0.id

    category1 = Category(title="Smartphones", parent_id=category_0_id)
    category2 = Category(title="Laptops", parent_id=category_0_id)
    session.add_all([category1, category2])
    session.flush()
    category_1_id = category1.id
    category_2_id = category2.id

    category3 = Category(title="Android Phones", parent_id=category_1_id)
    category4 = Category(title="iPhones", parent_id=category_1_id)
    category5 = Category(title="Gaming Laptops", parent_id=category_2_id)

    session.add_all([category3, category4, category5])
    session.commit()
    

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = Session(bind=bind)
    
    # Remove the data
    session.query(Category).filter(Category.title.in_(['Electronics', 'Smartphones', 'Laptops', 'Android Phones', 'iPhones', 'Gaming Laptops'])).delete()
    session.commit()